version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRAS_USER: wabsadmin
      POSTGRES_PASSWORD: MyWABS12345*
      POSTGRES_DB: wabsdb

  app:
    image: wabspg
    ports:
      - "8080:8080"
    depends_on:
      - db
